name: jersey_artwork
services:
- name: web
  source_dir: /
  github:
    repo: jgalan247/jersey_artwork
    branch: demo  # Use demo branch
  run_command: gunicorn --worker-tmp-dir /dev/shm artworks.wsgi
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  env:
  - key: DJANGO_SETTINGS_MODULE
    value: artworks.settings_demo
  - key: SECRET_KEY
    value: ${SECRET_KEY}
  - key: APP_DOMAIN
    value: jerseyhomepage.je
  routes:
  - path: /
databases:
- name: jersey-artwork-db
  engine: PG
  version: "15"
  size: db-s-dev-database