# Generated by Django 4.2.16 on 2025-09-14 15:49

import artworks.models
import artworks.validators
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='main_image',
            field=models.ImageField(help_text='Maximum file size: 5MB. Allowed formats: JPEG, PNG, WebP', upload_to=artworks.models.Artwork.artwork_upload_path, validators=[artworks.validators.FileValidator.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='stock_quantity',
            field=models.IntegerField(default=1, help_text='For prints or reproductions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(help_text='Maximum file size: 5MB. Allowed formats: JPEG, PNG, WebP', upload_to=artworks.models.ArtworkImage.gallery_upload_path, validators=[artworks.validators.FileValidator.validate_image_upload]),
        ),
    ]
